# Copyright (c) 2024 Кочуров Владислав Евгеньевич

name: kolibri-ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build native
        run: make build
      - name: Run tests
        run: make test
      - name: Bench placeholder
        run: ./kolibri.sh bench
